"use client"
import { InboxTable } from "@/components/security/tabInbox"
import React from "react"
import { CustomSelect } from "@/components/custom/customSelect"

const customs = [
    {
      "signal_id": "SIGNAL-20250704-0001",
      "timestamp": "2025-07-04T14:23:11Z",
      "severity": "high",
      "score": 0.93,
      "title": "Suspicious PowerShell activity on DESKTOP-SEC1",
      "risk": "vulnerability exploitation",
      "status": "pending",
      "feedback": "pending",
      "type": "attack",
      "hostname": "DESKTOP-SEC1",
      "host_ip": "192.168.1.12",
      "user": "ADMIN-PC\\manuela",
      "source_engines": ["ai_engine", "static_rule_engine"],
      "rule_id": "high-cpu-shell",
      "cluster_id": "cluster-42",
      "technique_id": "T1059",
      "technique_name": "Command and Scripting Interpreter",
      "tactics": ["Execution", "Defense Evasion"],
      "description": "AI detected high CPU usage by powershell.exe launched by user ADMIN-PC\\manuela, combined with potential evasion behavior. May indicate exploitation or malicious script."
    },
    {
      "signal_id": "SIGNAL-20250704-0002",
      "timestamp": "2025-07-04T10:02:43Z",
      "severity": "medium",
      "score": 0.65,
      "title": "Multiple failed logins on SRV-FINANCE",
      "risk": "credential brute force",
      "status": "pending",
      "feedback": "pending",
      "type": "credential access",
      "hostname": "SRV-FINANCE",
      "host_ip": "192.168.2.10",
      "user": "corp\\service",
      "source_engines": ["static_rule_engine"],
      "rule_id": "failed-login-threshold",
      "cluster_id": null,
      "technique_id": "T1110",
      "technique_name": "Brute Force",
      "tactics": ["Credential Access"],
      "description": "Several consecutive failed login attempts detected on SRV-FINANCE by user corp\\service, suggesting potential brute force attempt."
    },
    {
      "signal_id": "SIGNAL-20250703-0003",
      "timestamp": "2025-07-03T18:55:00Z",
      "severity": "high",
      "score": 0.89,
      "title": "Large data upload from DB-SERVER to unknown IP",
      "risk": "data exfiltration",
      "status": "pending",
      "feedback": "pending",
      "type": "data exfiltration",
      "hostname": "DB-SERVER",
      "host_ip": "192.168.3.20",
      "user": "dba\\paul",
      "source_engines": ["ai_engine"],
      "rule_id": null,
      "cluster_id": "cluster-56",
      "technique_id": "T1041",
      "technique_name": "Exfiltration Over C2 Channel",
      "tactics": ["Exfiltration"],
      "description": "Unusually large outbound transfer from DB-SERVER to an unknown external IP detected, outside normal business hours. May indicate data theft."
    },
    {
      "signal_id": "SIGNAL-20250703-0004",
      "timestamp": "2025-07-03T09:15:29Z",
      "severity": "low",
      "score": 0.35,
      "title": "Unusual process startup on TEST-VM",
      "risk": "potential misuse",
      "status": "ignored",
      "feedback": "false_positive",
      "type": "attack",
      "hostname": "TEST-VM",
      "host_ip": "192.168.4.44",
      "user": "admin\\test",
      "source_engines": ["static_rule_engine"],
      "rule_id": "unusual-process",
      "cluster_id": null,
      "technique_id": "T1082",
      "technique_name": "System Information Discovery",
      "tactics": ["Discovery"],
      "description": "A rare process was launched on TEST-VM. Analyst review marked this as a false positive due to test environment activity."
    },
    {
      "signal_id": "SIGNAL-20250702-0005",
      "timestamp": "2025-07-02T23:11:02Z",
      "severity": "medium",
      "score": 0.70,
      "title": "Suspicious RDP connection from external IP",
      "risk": "unauthorized access",
      "status": "validated",
      "feedback": "validated",
      "type": "lateral movement",
      "hostname": "APP-HOST",
      "host_ip": "192.168.5.55",
      "user": "corp\\alice",
      "source_engines": ["ai_engine"],
      "rule_id": null,
      "cluster_id": "cluster-22",
      "technique_id": "T1021",
      "technique_name": "Remote Services",
      "tactics": ["Lateral Movement"],
      "description": "An RDP session was initiated from an external IP address to APP-HOST by user corp\\alice, outside normal working hours."
    },
    {
      "signal_id": "SIGNAL-20250702-0006",
      "timestamp": "2025-07-02T14:44:30Z",
      "severity": "high",
      "score": 0.95,
      "title": "Process attempting to disable antivirus on DESKTOP-SEC2",
      "risk": "defense evasion",
      "status": "pending",
      "feedback": "pending",
      "type": "attack",
      "hostname": "DESKTOP-SEC2",
      "host_ip": "192.168.6.66",
      "user": "user\\john",
      "source_engines": ["ai_engine", "static_rule_engine"],
      "rule_id": "disable-av-detected",
      "cluster_id": "cluster-33",
      "technique_id": "T1562",
      "technique_name": "Impair Defenses",
      "tactics": ["Defense Evasion"],
      "description": "Detected attempt to disable antivirus service on DESKTOP-SEC2 by process launched by user\\john. Potential malicious behavior aiming to bypass security controls."
    },
    {
      "signal_id": "SIGNAL-20250704-0001",
      "timestamp": "2025-07-04T14:23:11Z",
      "severity": "high",
      "score": 0.93,
      "title": "Suspicious PowerShell activity on DESKTOP-SEC1",
      "risk": "vulnerability exploitation",
      "status": "pending",
      "feedback": "pending",
      "type": "attack",
      "hostname": "DESKTOP-SEC1",
      "host_ip": "192.168.1.12",
      "user": "ADMIN-PC\\manuela",
      "source_engines": ["ai_engine", "static_rule_engine"],
      "rule_id": "high-cpu-shell",
      "cluster_id": "cluster-42",
      "technique_id": "T1059",
      "technique_name": "Command and Scripting Interpreter",
      "tactics": ["Execution", "Defense Evasion"],
      "description": "AI detected high CPU usage by powershell.exe launched by user ADMIN-PC\\manuela, combined with potential evasion behavior. May indicate exploitation or malicious script."
    },
    {
      "signal_id": "SIGNAL-20250704-0002",
      "timestamp": "2025-07-04T10:02:43Z",
      "severity": "medium",
      "score": 0.65,
      "title": "Multiple failed logins on SRV-FINANCE",
      "risk": "credential brute force",
      "status": "pending",
      "feedback": "pending",
      "type": "credential access",
      "hostname": "SRV-FINANCE",
      "host_ip": "192.168.2.10",
      "user": "corp\\service",
      "source_engines": ["static_rule_engine"],
      "rule_id": "failed-login-threshold",
      "cluster_id": null,
      "technique_id": "T1110",
      "technique_name": "Brute Force",
      "tactics": ["Credential Access"],
      "description": "Several consecutive failed login attempts detected on SRV-FINANCE by user corp\\service, suggesting potential brute force attempt."
    },
    {
      "signal_id": "SIGNAL-20250703-0003",
      "timestamp": "2025-07-03T18:55:00Z",
      "severity": "high",
      "score": 0.89,
      "title": "Large data upload from DB-SERVER to unknown IP",
      "risk": "data exfiltration",
      "status": "pending",
      "feedback": "pending",
      "type": "data exfiltration",
      "hostname": "DB-SERVER",
      "host_ip": "192.168.3.20",
      "user": "dba\\paul",
      "source_engines": ["ai_engine"],
      "rule_id": null,
      "cluster_id": "cluster-56",
      "technique_id": "T1041",
      "technique_name": "Exfiltration Over C2 Channel",
      "tactics": ["Exfiltration"],
      "description": "Unusually large outbound transfer from DB-SERVER to an unknown external IP detected, outside normal business hours. May indicate data theft."
    },
    {
      "signal_id": "SIGNAL-20250703-0004",
      "timestamp": "2025-07-03T09:15:29Z",
      "severity": "low",
      "score": 0.35,
      "title": "Unusual process startup on TEST-VM",
      "risk": "potential misuse",
      "status": "ignored",
      "feedback": "false_positive",
      "type": "attack",
      "hostname": "TEST-VM",
      "host_ip": "192.168.4.44",
      "user": "admin\\test",
      "source_engines": ["static_rule_engine"],
      "rule_id": "unusual-process",
      "cluster_id": null,
      "technique_id": "T1082",
      "technique_name": "System Information Discovery",
      "tactics": ["Discovery"],
      "description": "A rare process was launched on TEST-VM. Analyst review marked this as a false positive due to test environment activity."
    },
    {
      "signal_id": "SIGNAL-20250702-0005",
      "timestamp": "2025-07-02T23:11:02Z",
      "severity": "medium",
      "score": 0.70,
      "title": "Suspicious RDP connection from external IP",
      "risk": "unauthorized access",
      "status": "validated",
      "feedback": "validated",
      "type": "lateral movement",
      "hostname": "APP-HOST",
      "host_ip": "192.168.5.55",
      "user": "corp\\alice",
      "source_engines": ["ai_engine"],
      "rule_id": null,
      "cluster_id": "cluster-22",
      "technique_id": "T1021",
      "technique_name": "Remote Services",
      "tactics": ["Lateral Movement"],
      "description": "An RDP session was initiated from an external IP address to APP-HOST by user corp\\alice, outside normal working hours."
    },
    {
      "signal_id": "SIGNAL-20250702-0006",
      "timestamp": "2025-07-02T14:44:30Z",
      "severity": "high",
      "score": 0.95,
      "title": "Process attempting to disable antivirus on DESKTOP-SEC2",
      "risk": "defense evasion",
      "status": "pending",
      "feedback": "pending",
      "type": "attack",
      "hostname": "DESKTOP-SEC2",
      "host_ip": "192.168.6.66",
      "user": "user\\john",
      "source_engines": ["ai_engine", "static_rule_engine"],
      "rule_id": "disable-av-detected",
      "cluster_id": "cluster-33",
      "technique_id": "T1562",
      "technique_name": "Impair Defenses",
      "tactics": ["Defense Evasion"],
      "description": "Detected attempt to disable antivirus service on DESKTOP-SEC2 by process launched by user\\john. Potential malicious behavior aiming to bypass security controls."
    }
  ]

export default function SecurityPage () {
    return (
        <section>
            <div className="px-16 py-8 space-y-8">
                <div className='flex items-center space-x-4'>
                    <CustomSelect type='TYPE' placeholder='ATTACK' elements={[]}/>
                    <CustomSelect type='Timeline' placeholder='7 Days' elements={[]}/>
                    <CustomSelect type='HOST' placeholder='Hostname' elements={[]}/>
                </div>
                <div className={`w-full max-h-[500px] border rounded mb-8`}>
                    <InboxTable dataInbox={customs} />
                </div>
            </div>
        </section>
    )
}